#!/usr/bin/env python

import sys, os

SERVER_TEMPLATE="""# Autogenerated server file
cd /etc/openvpn
dev			%(TYPE)s
local			0.0.0.0
port			1194
proto			%(PROTO)s
server			10.0.0.0 255.255.0.0
push			"route 10.0.0.0 255.255.0.0"
push			"redirect-gateway"
route			192.168.10.0 255.255.255.0
route			172.16.0.0 255.240.0.0
client-config-dir	ccd
client-to-client
tls-server
dh			dh%(DH_SIZE)s.pem
ca			CA_cert.pem
cert			certs/%(HOSTNAME)s.cert
key			keys/%(HOSTNAME)s.key
crl-verify		crl/crl.pem
tls-auth		ta.key 0
comp-lzo
keepalive		10 120
tun-mtu			1500
mssfix			1450
persist-key
persist-tun
user			openvpn
group			openvpn
verb			3
"""

CLIENT_TEMPLATE = """# Autogenerated config
client
dev		%(TYPE)s
proto		%(PROTO)s
remote		%(HOSTNAME)s
tls-client
tls-remote	"%(HOSTNAME)s"
ca		"CA_cert.pem"
cert		"certs/%(NAME)s.cert"
key		"keys/%(NAME)s.key"
tls-auth	"ta.key" 1
ns-cert-type	server
comp-lzo
tun-mtu		1500
mssfix		1450
verb		3
"""

if __name__ == '__main__':
    data = dict()
    if sys.argv[1] == 'server':
        data['HOSTNAME'], data['DH_SIZE'], data['PROTO'], data['TYPE'] = sys.argv[2:6]

        print SERVER_TEMPLATE % data
    elif sys.argv[1] == 'client' or sys.argv[1] == 'clientwin':
        data['HOSTNAME'], data['NAME'], data['PROTO'], data['TYPE'] = sys.argv[2:6]

        if sys.argv[1] == 'clientwin':
            print (CLIENT_TEMPLATE % data).replace('\n', '\r\n')
        elif sys.argv[1] == 'client':
            print CLIENT_TEMPLATE % data